### ISSUE TITLE
Call to function "yamldecode" failed

### ISSUE THREAD

**Issue by vpasnur** [Infostrux-Solutions/terraform-snowflake-rbac#33]
Hello,
I am testing the RBAC module and the spec.yml file is in the same location as other .tf files. While running terraform plan, I am receiving below error.  Is there anything I should be trying out? 

I given below location in plan output:

```
var.spec_file_path
  The path to the RBAC specification file.

  Enter a value: ~/Documents/snowflakerbac_1/spec.yml
```

```
 Error: Error in function call
│
│   on .terraform/modules/rbac/locals.tf line 4, in locals:
│    4:   spec = yamldecode(file(var.spec_file_path))
│     ├────────────────
│     │ var.spec_file_path is "spec.yml"
│
│ Call to function "yamldecode" failed: on line 7, column 12: did not find
│ expected key.
```

**Comment by augustorosa** [comment]
Hi, got your open issue. we are going to look.

**Comment by mustafa-hammer** [comment]
@vpasnur would you be able to provide the contents of your `spec.yml` file?

**Comment by mustafa-hammer** [comment]
@vpasnur The error implies to me one of two issues:

1. The file path isn't correct and the project isn't able to load the values
2. The format of your `spec.yml` doesn't match the spec outlined [here](https://github.com/Infostrux-Solutions/mm-foodmarket-snowflake) 

Feel free to share the `spec.yml` and we can review it.

**Comment by vpasnur** [comment]
Hello All,
Attached is my spec.yml file. It's in the same location as other TF files.
Let me know if any modifications are needed to this spec.yml file. Thank you

**Comment by mustafa-hammer** [comment]
@vpasnur do you mind pasting the spec.yml file here as the email reply wont attach it to here

**Comment by vpasnur** [comment]
Yeah. Sure. Here is the info.

databases:
  database_name:
          privileges:
          database:
            read:
              roles:
                - ACCOUNTADMIN
           schemas:
             read:
               roles:
                 - SYSADMIN

            roles:
              role_name:
                grant_to:
                  roles:
                    - SYSADMIN
roles:
  role_name:
    grant_to:
      roles:
        - SYSADMIN

warehouses:
  warehouse_name:
    privileges:
      roles:
        - SYSADMIN

**Comment by mustafa-hammer** [comment]
The spacing for this `spec.yml` doesn't seem correct to me.. spacing is very important in yml. 

```
databases:
  database_name:
    privileges:
      database:
        read:
          roles:
            - ACCOUNTADMIN
      schemas:
        read:
          roles:
            - SYSADMIN
      roles:
        role_name:
          grant_to:
            roles:
              - SYSADMIN
roles:
  role_name:
    grant_to:
      roles:
        - SYSADMIN

warehouses:
  warehouse_name:
    privileges:
      roles:
        - SYSADMIN
```

**Comment by vpasnur** [comment]
Thanks for pointing that out. i used yaml formatter and noticed a tab space
given extra.
Can I know where I should define database name, schema and table name? I am
currently getting below errors.

Error: Invalid function argument
│
│   on locals.tf line 65, in locals:
│   65:     if contains(keys(spec.privileges), "database")
│     ├────────────────
│     │ spec.privileges is null
│
│ Invalid value for "inputMap" parameter: argument must not be null.
╵
╷
│ Error: Invalid function argument
│
│   on locals.tf line 104, in locals:
│  104:     if contains(keys(spec.privileges), "schemas")
│     ├────────────────
│     │ spec.privileges is null
│
│ Invalid value for "inputMap" parameter: argument must not be null.
╵
╷
│ Error: Invalid function argument
│
│   on locals.tf line 143, in locals:
│  143:     if contains(keys(spec.privileges), "tables")
│     ├────────────────
│     │ spec.privileges is null
│
│ Invalid value for "inputMap" parameter: argument must not be null.

**Comment by mustafa-hammer** [comment]
```
databases:
  database_name:
    privileges:
      database:
        read:
          roles:
            - ACCOUNTADMIN
      schemas:
        read:
          roles:
            - SYSADMIN
      roles:
        role_name:
          grant_to:
            roles:
              - SYSADMIN
roles:
  role_name:
    grant_to:
      roles:
        - SYSADMIN

warehouses:
  warehouse_name:
    privileges:
      roles:
        - SYSADMIN
```

In this example, the database name is `database_name`, the role name is `role_name` and warehouse is `warehouse_name`. Just replace `database_name`, `role_name` and `warehouse_name` with the values you want
